[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "mynns"
version = "0.0.1"

[tool.setuptools.packages.find]
where = ["src"]
include = ["mynns*"]